# fly.toml app configuration file generated for bananabit on 2025-08-26T04:14:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bananabit'
primary_region = 'fra'

[build]

[env]
  # Application Configuration
  PORT = "8080"
  IP = "0.0.0.0"
  # Database URL - using fly.io volumes for persistence
  DATABASE_URL = "sqlite:///data/cms.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Volume for database persistence
[mounts]
  source = "cms_data"
  destination = "/data"
