use dioxus::prelude::*;
use super::{Extension, ExtensionRoute, ExtensionComponent};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// SEO metadata structure
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SeoMeta {
    pub title: String,
    pub description: String,
    pub keywords: String,
    pub og_title: Option<String>,
    pub og_description: Option<String>,
    pub og_image: Option<String>,
    pub canonical_url: Option<String>,
    pub robots: String, // "index,follow", "noindex,nofollow", etc.
    pub lang: String,
    pub author: Option<String>,
}

impl Default for SeoMeta {
    fn default() -> Self {
        Self {
            title: "BananaBit CMS".to_string(),
            description: "Modern, extension-based content management system".to_string(),
            keywords: "cms, content management, rust, dioxus".to_string(),
            og_title: None,
            og_description: None,
            og_image: None,
            canonical_url: None,
            robots: "index,follow".to_string(),
            lang: "en".to_string(),
            author: None,
        }
    }
}

/// Sitemap entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SitemapEntry {
    pub url: String,
    pub last_modified: String,
    pub change_frequency: String, // always, hourly, daily, weekly, monthly, yearly, never
    pub priority: f32, // 0.0 to 1.0
}

/// SEO extension for search engine optimization
pub struct SeoExtension {
    page_meta: HashMap<String, SeoMeta>, // url -> meta
    sitemap_entries: Vec<SitemapEntry>,
    global_meta: SeoMeta,
}

impl SeoExtension {
    pub fn new() -> Self {
        Self {
            page_meta: HashMap::new(),
            sitemap_entries: Vec::new(),
            global_meta: SeoMeta::default(),
        }
    }
    
    pub fn set_page_meta(&mut self, url: &str, meta: SeoMeta) {
        self.page_meta.insert(url.to_string(), meta);
    }
    
    pub fn get_page_meta(&self, url: &str) -> SeoMeta {
        self.page_meta.get(url).cloned().unwrap_or_else(|| self.global_meta.clone())
    }
    
    pub fn set_global_meta(&mut self, meta: SeoMeta) {
        self.global_meta = meta;
    }
    
    pub fn add_sitemap_entry(&mut self, entry: SitemapEntry) {
        self.sitemap_entries.push(entry);
    }
    
    pub fn generate_sitemap_xml(&self) -> String {
        let mut xml = String::from(r#"<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
"#);
        
        for entry in &self.sitemap_entries {
            xml.push_str(&format!(
                r#"  <url>
    <loc>{}</loc>
    <lastmod>{}</lastmod>
    <changefreq>{}</changefreq>
    <priority>{:.1}</priority>
  </url>
"#,
                entry.url, entry.last_modified, entry.change_frequency, entry.priority
            ));
        }
        
        xml.push_str("</urlset>");
        xml
    }
    
    pub fn generate_robots_txt(&self) -> String {
        format!(
            r#"User-agent: *
Allow: /

Sitemap: /sitemap.xml

# Common crawl patterns
Disallow: /admin/
Disallow: /api/
Disallow: /*.json$
Disallow: /uploads/private/

# Generated by BananaBit CMS
"#
        )
    }
}

impl Extension for SeoExtension {
    fn id(&self) -> &'static str {
        "core.seo"
    }
    
    fn name(&self) -> &'static str {
        "SEO & Analytics"
    }
    
    fn version(&self) -> &'static str {
        "1.0.0"
    }
    
    fn init(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        // Add default sitemap entries
        self.add_sitemap_entry(SitemapEntry {
            url: "https://bananabit.dev/".to_string(),
            last_modified: chrono::Utc::now().format("%Y-%m-%d").to_string(),
            change_frequency: "daily".to_string(),
            priority: 1.0,
        });
        
        self.add_sitemap_entry(SitemapEntry {
            url: "https://bananabit.dev/post/welcome-to-bananabit-cms".to_string(),
            last_modified: chrono::Utc::now().format("%Y-%m-%d").to_string(),
            change_frequency: "monthly".to_string(),
            priority: 0.8,
        });
        
        // Set page-specific meta
        let post_meta = SeoMeta {
            title: "Welcome to BananaBit CMS".to_string(),
            description: "Discover the power of our modern, extension-based content management system built with Rust and Dioxus.".to_string(),
            keywords: "cms, rust, dioxus, content management, blogging".to_string(),
            og_title: Some("Welcome to BananaBit CMS".to_string()),
            og_description: Some("Modern, extension-based content management system".to_string()),
            og_image: Some("/uploads/bananabit-logo.png".to_string()),
            canonical_url: Some("https://bananabit.dev/post/welcome-to-bananabit-cms".to_string()),
            robots: "index,follow".to_string(),
            lang: "en".to_string(),
            author: Some("BananaBit Team".to_string()),
        };
        
        self.set_page_meta("/post/welcome-to-bananabit-cms", post_meta);
        
        Ok(())
    }
    
    fn routes(&self) -> Vec<ExtensionRoute> {
        vec![
            ExtensionRoute {
                path: "/admin/seo".to_string(),
                requires_auth: true,
                admin_only: false,
            },
            ExtensionRoute {
                path: "/sitemap.xml".to_string(),
                requires_auth: false,
                admin_only: false,
            },
            ExtensionRoute {
                path: "/robots.txt".to_string(),
                requires_auth: false,
                admin_only: false,
            },
        ]
    }
    
    fn components(&self) -> Vec<ExtensionComponent> {
        vec![
            ExtensionComponent {
                name: "SeoManager".to_string(),
                description: "Manage SEO settings and metadata".to_string(),
            },
            ExtensionComponent {
                name: "MetaTags".to_string(),
                description: "Render meta tags for pages".to_string(),
            },
            ExtensionComponent {
                name: "SeoAnalytics".to_string(),
                description: "SEO performance analytics".to_string(),
            },
        ]
    }
}

/// SEO manager component for admin
#[component]
pub fn SeoManager() -> Element {
    rsx! {
        div { class: "seo-manager",
            h2 { "SEO & Analytics" }
            p { class: "description",
                "Manage search engine optimization settings, meta tags, and analytics for your site."
            }
            
            div { class: "seo-tabs",
                div { class: "tab-navigation",
                    button { class: "tab-button active", "General Settings" }
                    button { class: "tab-button", "Page Meta" }
                    button { class: "tab-button", "Sitemap" }
                    button { class: "tab-button", "Analytics" }
                }
                
                div { class: "tab-content",
                    div { class: "tab-panel active",
                        h3 { "Global SEO Settings" }
                        
                        div { class: "form-section",
                            div { class: "form-group",
                                label { "Site Title" }
                                input {
                                    r#type: "text",
                                    value: "BananaBit CMS",
                                    placeholder: "Your site title"
                                }
                            }
                            
                            div { class: "form-group",
                                label { "Site Description" }
                                textarea {
                                    placeholder: "Brief description of your site",
                                    rows: "3",
                                    "Modern, extension-based content management system built with Rust and Dioxus."
                                }
                            }
                            
                            div { class: "form-group",
                                label { "Keywords" }
                                input {
                                    r#type: "text",
                                    value: "cms, rust, dioxus, content management",
                                    placeholder: "Comma-separated keywords"
                                }
                            }
                            
                            div { class: "form-row",
                                div { class: "form-group",
                                    label { "Default Language" }
                                    select {
                                        option { value: "en", "English" }
                                        option { value: "es", "Spanish" }
                                        option { value: "fr", "French" }
                                        option { value: "de", "German" }
                                    }
                                }
                                
                                div { class: "form-group",
                                    label { "Robots Default" }
                                    select {
                                        option { value: "index,follow", "Index, Follow" }
                                        option { value: "noindex,nofollow", "No Index, No Follow" }
                                        option { value: "index,nofollow", "Index, No Follow" }
                                        option { value: "noindex,follow", "No Index, Follow" }
                                    }
                                }
                            }
                        }
                        
                        h3 { "Open Graph Settings" }
                        div { class: "form-section",
                            div { class: "form-group",
                                label { "Default OG Image" }
                                div { class: "file-input-group",
                                    input {
                                        r#type: "text",
                                        value: "/uploads/bananabit-logo.png",
                                        placeholder: "Image URL or path"
                                    }
                                    button { class: "btn btn-outline", "Browse" }
                                }
                            }
                            
                            div { class: "form-group",
                                label { "Site Author" }
                                input {
                                    r#type: "text",
                                    value: "BananaBit Team",
                                    placeholder: "Default author name"
                                }
                            }
                        }
                        
                        div { class: "form-actions",
                            button { class: "btn btn-primary", "Save Settings" }
                            button { class: "btn btn-outline", "Reset to Default" }
                        }
                    }
                }
            }
            
            div { class: "seo-tools",
                h3 { "SEO Tools" }
                div { class: "tools-grid",
                    div { class: "tool-card",
                        h4 { "📊 Analytics Dashboard" }
                        p { "View search engine performance and traffic analytics" }
                        button { class: "btn btn-outline", "View Analytics" }
                    }
                    
                    div { class: "tool-card",
                        h4 { "🗺️ Generate Sitemap" }
                        p { "Automatically generate XML sitemap for search engines" }
                        button { class: "btn btn-outline", "Generate" }
                    }
                    
                    div { class: "tool-card",
                        h4 { "🤖 Robots.txt" }
                        p { "Configure search engine crawler behavior" }
                        button { class: "btn btn-outline", "Edit Robots.txt" }
                    }
                    
                    div { class: "tool-card",
                        h4 { "🔍 SEO Audit" }
                        p { "Analyze your site for SEO best practices" }
                        button { class: "btn btn-outline", "Run Audit" }
                    }
                }
            }
        }
        
        style { r#"
            .seo-manager {
                padding: 20px;
                max-width: 1200px;
                margin: 0 auto;
            }
            
            .description {
                color: var(--text-secondary, #a0aec0);
                margin-bottom: 30px;
            }
            
            .seo-tabs {
                background: var(--bg-secondary, #2d3748);
                border: 1px solid var(--border-color, #4a5568);
                border-radius: 8px;
                margin-bottom: 30px;
            }
            
            .tab-navigation {
                display: flex;
                border-bottom: 1px solid var(--border-color, #4a5568);
            }
            
            .tab-button {
                padding: 15px 20px;
                background: transparent;
                border: none;
                color: var(--text-secondary, #a0aec0);
                cursor: pointer;
                transition: all 0.2s ease;
                border-bottom: 2px solid transparent;
            }
            
            .tab-button:hover {
                color: var(--text-primary, #e2e8f0);
                background: var(--bg-tertiary, #4a5568);
            }
            
            .tab-button.active {
                color: var(--accent-primary, #63b3ed);
                border-bottom-color: var(--accent-primary, #63b3ed);
            }
            
            .tab-content {
                padding: 30px;
            }
            
            .form-section {
                margin-bottom: 30px;
            }
            
            .form-group {
                margin-bottom: 20px;
            }
            
            .form-row {
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 20px;
            }
            
            .form-group label {
                display: block;
                margin-bottom: 8px;
                color: var(--text-primary, #e2e8f0);
                font-weight: 500;
            }
            
            .form-group input,
            .form-group textarea,
            .form-group select {
                width: 100%;
                padding: 10px;
                border: 1px solid var(--border-color, #4a5568);
                border-radius: 6px;
                background: var(--bg-primary, #1a202c);
                color: var(--text-primary, #e2e8f0);
                font-size: 14px;
            }
            
            .file-input-group {
                display: flex;
                gap: 10px;
            }
            
            .file-input-group input {
                flex: 1;
            }
            
            .form-actions {
                display: flex;
                gap: 15px;
                margin-top: 30px;
            }
            
            .tools-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 20px;
                margin-top: 20px;
            }
            
            .tool-card {
                background: var(--bg-secondary, #2d3748);
                border: 1px solid var(--border-color, #4a5568);
                border-radius: 8px;
                padding: 20px;
                text-align: center;
            }
            
            .tool-card h4 {
                margin: 0 0 10px 0;
                color: var(--text-primary, #e2e8f0);
            }
            
            .tool-card p {
                color: var(--text-secondary, #a0aec0);
                font-size: 14px;
                margin-bottom: 15px;
            }
            
            .btn {
                padding: 10px 20px;
                border-radius: 6px;
                border: 1px solid;
                cursor: pointer;
                font-weight: 500;
                transition: all 0.2s ease;
                text-decoration: none;
                display: inline-block;
            }
            
            .btn-primary {
                background: var(--accent-primary, #63b3ed);
                color: #ffffff;
                border-color: var(--accent-primary, #63b3ed);
            }
            
            .btn-primary:hover {
                background: var(--accent-secondary, #4299e1);
                border-color: var(--accent-secondary, #4299e1);
            }
            
            .btn-outline {
                background: transparent;
                color: var(--accent-primary, #63b3ed);
                border-color: var(--accent-primary, #63b3ed);
            }
            
            .btn-outline:hover {
                background: var(--accent-primary, #63b3ed);
                color: #ffffff;
            }
        "# }
    }
}

/// Meta tags component to render in document head
#[component]
pub fn MetaTags(meta: SeoMeta) -> Element {
    let og_title = meta.og_title.as_ref().unwrap_or(&meta.title);
    let og_description = meta.og_description.as_ref().unwrap_or(&meta.description);
    let author = meta.author.as_deref().unwrap_or("");
    
    rsx! {
        // Basic meta tags
        title { "{meta.title}" }
        meta { name: "description", content: "{meta.description}" }
        meta { name: "keywords", content: "{meta.keywords}" }
        meta { name: "author", content: "{author}" }
        meta { name: "robots", content: "{meta.robots}" }
        meta { name: "language", content: "{meta.lang}" }
        
        // Open Graph tags
        meta { property: "og:title", content: "{og_title}" }
        meta { property: "og:description", content: "{og_description}" }
        meta { property: "og:type", content: "website" }
        
        if let Some(ref og_image) = meta.og_image {
            meta { property: "og:image", content: "{og_image}" }
        }
        
        // Twitter Card tags
        meta { name: "twitter:card", content: "summary_large_image" }
        meta { name: "twitter:title", content: "{og_title}" }
        meta { name: "twitter:description", content: "{og_description}" }
        
        // Canonical URL
        if let Some(ref canonical) = meta.canonical_url {
            link { rel: "canonical", href: "{canonical}" }
        }
        
        // Additional SEO tags
        meta { name: "viewport", content: "width=device-width, initial-scale=1.0" }
        meta { name: "format-detection", content: "telephone=no" }
    }
}