[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"]  }
api = { workspace = true }
pulldown-cmark = "0.9.3"
syntect = { version = "5.1.0", default-features = false, features = ["default-fancy"] }
