[application]

[web.app]

# HTML title tag content
title = "bananabit"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
    "assets/main.css",
    "assets/components.css", 
    "assets/blog.css",
    "assets/markdown.css",
    "assets/syntax.css"
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
